### PR TITLE
Change of Registration Email Processor

### PR DESCRIPTION
**Pull request by lekshmimallika-aot**
*Issue #:* /bcgov/entity#10759

*Description of changes:*
Added  processor for change of registration
Added templates
Added unit tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by vysakh-menon-aot — APPROVED** [review]

**Comment by lekshmimallika-aot** [comment]
@argush3 @vysakh-menon-aot Any suggestions on improving code coverage?

**Comment by argush3** [comment]
> @argush3 @vysakh-menon-aot Any suggestions on improving code coverage?

I guess we can try adding some tests to cover some of the files with lower coverage here.  
image

**Comment by lekshmimallika-aot** [comment]
> > @argush3 @vysakh-menon-aot Any suggestions on improving code coverage?
> 
> I guess we can try adding some tests to cover some of the files with lower coverage here. image

Will  try as a follow up PR

**Review by argush3 — CHANGES_REQUESTED** [review]
looks good.  can we also add two entries to this tracker test for change registration?

https://github.com/bcgov/lear/blob/2edafa9db39ab1d8d8254f5dcc2660c7626ad104/queue_services/entity-emailer/tests/unit/test_tracker.py#L203-L218

**Review by argush3 — APPROVED** [review]

**Pull request merged**
