### PR TITLE
Getting some errors on the test locations

### PR DESCRIPTION
**Pull request by rstens**
Updating to the exact locations

*Issue #:* /bcgov/entity###

*Description of changes:*
Remove some of the test paths and refined the others as we are getting errors on the scanning.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by thorwolpert** [comment]
I think this was superseded by the other PR, so closing.

**Comment by rstens** [comment]
> I think this was superseded by the other PR, so closing.

Actually, this was a fix, so by closing this the fix has not been applied.

**Comment by rstens** [comment]
Sorry this was a fix that needs to go in, right now SoanrCloud is
complaining abot misconfig and this ws to correct the issue.

**Comment by JohnamLane** [comment]
re-opened based on Roland's comment above.

**Pull request merged**
