### PR TITLE
24985 skip payment for sandbox

### PR DESCRIPTION
**Pull request by vysakh-menon-aot**
*Issue #:* /bcgov/entity#24985

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by thorwolpert** [comment]
Why? Payments work in the sandbox

**Comment by vysakh-menon-aot** [comment]
> Why? Payments work in the sandbox

Added you to the discussion in Teams

**Comment by thorwolpert** [comment]
> > Why? Payments work in the sandbox
> 
> Added you to the discussion in Teams

It's been working in PPR/Search for a few years now

**Comment by seeker25** [comment]
sorry about that @vysakh-menon-aot

**Pull request closed without merging**
