### PR TITLE
fix for bug 2044

### PR DESCRIPTION
**Pull request by peter-freshworks**
*Issue #:* /bcgov/entity#2044

*Description of changes:*
Task list not taking pending filings into account for B-Comp. Fix the todo-list constructor method to account for pending/draft filings for non CO-OP entities as well.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by katiemcgoff** [comment]
Hi Peter, are there any tests that need to be updated or added?

**Comment by peter-freshworks** [comment]
> y

We have coverage for tasks/todo lists, but I can add something a bit more specific for this bug

**Comment by peter-freshworks** [comment]
> Hi Peter, are there any tests that need to be updated or added?

We have coverage for tasks/todo lists, but I can add something a bit more specific for this bug

**Comment by peter-freshworks** [comment]
> Hi Peter, are there any tests that need to be updated or added?

I stand corrected, I see no coverage for b-comp task lists and pending filings

**Pull request merged**
