### PR TITLE
Share structure for COLIN API

### PR DESCRIPTION
**Pull request by peter-freshworks**
*Issue #:* /bcgov/entity#3034

*Description of changes:*
Add model, endpoints, and tests for interacting with share_struct, share_struct_cls, and share_series tables in COLIN

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by kialj876** [comment]
I approved but had one question about the json that gets returned with the post: should it be returning the parties as well? Right now it just returns the office and share structure, but no section for the parties (not sure if this matters at all or not)

**Comment by peter-freshworks** [comment]
> I approved but had one question about the json that gets returned with the post: should it be returning the parties as well? Right now it just returns the office and share structure, but no section for the parties (not sure if this matters at all or not)

You are correct...I must've overlooked that in the step 2 ticket...should we make a new ticket for that or should I tack that on here?

**Comment by kialj876** [comment]
> > I approved but had one question about the json that gets returned with the post: should it be returning the parties as well? Right now it just returns the office and share structure, but no section for the parties (not sure if this matters at all or not)
> 
> You are correct...I must've overlooked that in the step 2 ticket...should we make a new ticket for that or should I tack that on here?

If you have time and its quick (under an hour) I would just add it in

**Comment by peter-freshworks** [comment]
> > > I approved but had one question about the json that gets returned with the post: should it be returning the parties as well? Right now it just returns the office and share structure, but no section for the parties (not sure if this matters at all or not)
> > 
> > 
> > You are correct...I must've overlooked that in the step 2 ticket...should we make a new ticket for that or should I tack that on here?
> 
> If you have time and its quick (under an hour) I would just add it in

done

**Pull request merged**
