### PR TITLE
21020 Fix wrong AR year is being displayed in the annual report output

### PR DESCRIPTION
**Pull request by leodube-aot**
*Issue #:* /bcgov/entity#21020

*Description of changes:*
- Fixed incorrect AR year in the outputs. A similar issue was fixed previously for co-ops https://github.com/bcgov/lear/pull/1105

Before:
Screenshot 2024-05-14 at 9 49 01 AM

After:
Screenshot 2024-05-14 at 9 49 06 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by chenhongjing — APPROVED** [review]

**Comment by argush3** [comment]
can we fix the linting error?

**Comment by leodube-aot** [comment]
> can we fix the linting error?

Yeah I'll have a look, not sure where it got caused from but I'll fix it.

**Comment by argush3** [comment]
> > can we fix the linting error?
> 
> Yeah I'll have a look, not sure where it got caused from but I'll fix it.

Thanks, yeah I think we may have missed it from another change.

**Review by argush3 — APPROVED** [review]

**Comment by leodube-aot** [comment]
> Thanks, yeah I think we may have missed it from another change.

Weird, it was coming from `/reports/report.py` (last updated 2 weeks ago) and `/resources/v1/business/business_filings.py` (last updated 3 months ago), and I didn't see these linting errors thrown for recent PRs. Couldn't even replicate it on my machine. Looks like it's fixed now.

**Pull request merged**
