### PR TITLE
14486 extract COLIN corp data script

### PR DESCRIPTION
**Pull request by argush3**
*Issue #:* /bcgov/entity#14486

*Description of changes:*

* Added script(`data-tool/transfer_cprd_corps.sql`) for transferring COLIN corps data to a postgres extract db.  This postgres extract db will be used by the corps data migration pipeline to clean/transform and push corps into LEAR db.
* Added ddl for postgres extract db
* Added README(`README_COLIN_Corps_Extract`) providing details of extract process

Example of a full corp extract from COLIN:

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by vysakh-menon-aot — APPROVED** [review]

**Comment by droberts27** [comment]
@argush3 It looks like the following got missed:
corporation.last_ar_filed_dt
filing.court_order_num
filing_user.bcol_acct_num
filing_user.role_typ_cd
ledger_text.ledger_text_dts
share_struct_cls.class_nme

**Comment by droberts27** [comment]
@argush3 If you avoid the events that were copied from LEAR to CPRD then it will work.  The other tables will still have the rows we don’t want but when you loop through the events those rows will not be processed.  If you loop through FILING instead of EVENT then we can add the following line to the FILING extract.

and event_typ_cd not in ('BNUPD','ADDLEDGR') -- not doing anything
and event_id NOT in (select event_id from filing_user where user_id='BCOMPS')

**Comment by argush3** [comment]
> @argush3 It looks like the following got missed: corporation.last_ar_filed_dt filing.court_order_num filing_user.bcol_acct_num filing_user.role_typ_cd ledger_text.ledger_text_dts share_struct_cls.class_nme

Updated extract script to include missed fields in select statements - https://github.com/bcgov/lear/pull/1862/commits/8da047fc38e42f5909dcae69d9dbef96a5a1fa9a

**Comment by argush3** [comment]
> 

Update transfer script to deal with scenario where a BEN later alters to a BC company - https://github.com/bcgov/lear/pull/1862/commits/c7f564f8726c7483311fcda19a1967326e3c1e84

**Comment by argush3** [comment]
@droberts27 I've updated the transfer script to deal with scenario where a BEN later alters to a BC company - https://github.com/bcgov/lear/pull/1862/commits/c7f564f8726c7483311fcda19a1967326e3c1e84

**Comment by droberts27** [comment]
The corp_involved table contains the amalgamaTING corps (ting).  corporation.corp_num is the amalgamaTED corp (ted).  I have changed c.corp_num to ci.corp_num.  More to come for this table.

select e.event_id,
       **CI.CORP_NUM,**
       ci.CORP_INVOLVE_ID,
from event e
   , CORP_INVOLVED ci
   , corporation c
where e.event_id = ci.event_id
  and c.corp_num = e.corp_num
  and corp_typ_cd in ('BC', 'C', 'ULC', 'CUL', 'CC', 'CCC', 'QA', 'QB', 'QC', 'QD', 'QE')

**Comment by argush3** [comment]
Updated transfer script to get corp_num from `ci.corp_num` for `corp_involved` table - https://github.com/bcgov/lear/pull/1862/commits/733663b4decef3a5ffe3b8eaaa2ae2d07bfa6c92

**Comment by droberts27** [comment]
@argush3 Just a reminder - the scripts have to run when there is no activity to ensure consistency

**Comment by argush3** [comment]
> @argush3 Just a reminder - the scripts have to run when there is no activity to ensure consistency

Sounds good.  If I do a full extract I will do it around 3am.

**Comment by droberts27** [comment]
Here is the extract SQL for corp_involved - amalgamaTING_businesses

select * from
(
select e.event_id, -- SELECT BY EVENT
       ci.CORP_NUM,
       ci.CORP_INVOLVE_ID,
       ci.CAN_JUR_TYP_CD,
       case ci.ADOPTED_CORP_IND
           when 'N' then 0
           when 'Y' then 1
           else 0
           end ADOPTED_CORP_IND,
       ci.HOME_JURI_NUM,
       ci.OTHR_JURI_DESC,
       ci.FOREIGN_NME
from event e
   , CORP_INVOLVED ci
   , corporation c
where e.event_id = ci.event_id
  and c.corp_num = e.corp_num
  and corp_typ_cd in ('BC', 'C', 'ULC', 'CUL', 'CC', 'CCC', 'QA', 'QB', 'QC', 'QD', 'QE')
  and event_typ_cd='CONVAMAL'
UNION ALL
select e.event_id, -- SELECT BY FILING
       ci.CORP_NUM,
       ci.CORP_INVOLVE_ID,
       ci.CAN_JUR_TYP_CD,
       case ci.ADOPTED_CORP_IND
           when 'N' then 0
           when 'Y' then 1
           else 0
           end ADOPTED_CORP_IND,
       ci.HOME_JURI_NUM,
       ci.OTHR_JURI_DESC,
       ci.FOREIGN_NME
from event e
   , CORP_INVOLVED ci
   , corporation c
   , filing f
where e.event_id = ci.event_id
  and c.corp_num = e.corp_num
  and e.event_id = f.event_id
  and corp_typ_cd in ('BC', 'C', 'ULC', 'CUL', 'CC', 'CCC', 'QA', 'QB', 'QC', 'QD', 'QE')
  and filing_typ_cd in ('AMALH','AMALV','AMALR',  'AMLHU','AMLVU','AMLRU',  'AMLHC','AMLVC','AMLRC')
)
order by event_id;

**Comment by droberts27** [comment]
@argush3 forgot to tag you on the previous comment

**Comment by droberts27** [comment]
@argush3 Here is the extract SQL for corp_involved - continue_in_historical_xpro

select e.event_id,
       ci.CORP_NUM
from event e
   , CORP_INVOLVED ci
   , corporation c
   , filing f
where e.event_id = ci.event_id
  and c.corp_num = e.corp_num
  and e.event_id = f.event_id
  and corp_typ_cd in ('BC', 'C', 'ULC', 'CUL', 'CC', 'CCC', 'QA', 'QB', 'QC', 'QD', 'QE')
  and filing_typ_cd in ('CONTI','CONTU','CONTC')
order by e.event_id;

**Comment by droberts27** [comment]
@argush3 I have updated the datamap spreadsheet for corp_involved and jurisdiction.  Optionally when a corp continues in it makes an xpro historical.  Since we will not have xpros in LEAR we will need to either copy them to LEAR or remotely select and update them in CPRD.

**Comment by argush3** [comment]
@droberts27 I have made made the changes to extract corp-involved amalgamating business and corp involved continue to two tables.  Also removed "end_event_id" from the jurisdiction table select.

**Pull request merged**
