### PR TITLE
Added tests for COD effective date, cancel payment, dir list by date.

### PR DESCRIPTION
**Pull request by katiemcgoff**
*Issue #:* /bcgov/entity#1982 (COD effective dates), /bcgov/entity#2122 (cancel payment)

*Description of changes:*
Added tests for COD effective date, cancel payment, dir list by date.

Also changed some test validation in COD and COA task list tests to make
more robust.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by katiemcgoff** [comment]
Highlighted tests in this screenshot are those that I changed or added (since diff'ing a postman collection is not helpful):

image

**Comment by JohnamLane** [comment]
The acceptance criteria for this includes it running in the pipeline using some form of data resetting. Has this portion of the ticket been looked at yet?

**Comment by katiemcgoff** [comment]
Sort of - in progress; I'll pull the ticket back.

Thanks,
Katie McGoff

**Comment by katiemcgoff** [comment]
@JohnamLane @riyazuddinsyed For these changes, regardless of the remaining task of the ticket - do you approve the added/changed tests for COD and Cancel Filing?

**Pull request merged**
