### PR TITLE
4923 - Added affiliation support to q_cli

### PR DESCRIPTION
**Pull request by andrepestana-aot**
*Issue #:* /bcgov/entity#4923

*Description of changes:*

 - Added affiliation support to q_cli
 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by thorwolpert** [comment]
I'd like the cloud_event to be the whole message and not a fragment
```
cloud_event_msg = create_cloud_event_msg(msg_id=str(uuid.uuid4()),
                                                 msg_type='bc.registry.business',
                                                 source=f'/businesses/{corp.identifier}',
                                                 time=datetime.utcfromtimestamp(time.time()).
                                                 replace(tzinfo=timezone.utc).isoformat(),
                                                 identifier=corp.identifier,
                                                 json_data_body={
                                                     'filing': {
                                                         'header': {'filingId': filing.id}
                                                     }}
                                                 )
                                                
```

**Comment by andrepestana-aot** [comment]
I have just realized that the GHA are not triggering the tests. Can we add that?

**Comment by andrepestana-aot** [comment]
@thorwolpert there's an issue with the GHA. Could you please check it?

**Comment by thorwolpert** [comment]
fixed the lint
the test fixtures for the DB are in a future PR.

**Review by thorwolpert — APPROVED** [review]

**Pull request merged**
