### PR TITLE
4711 entity filer updates for data loader

### PR DESCRIPTION
**Pull request by argush3**
*Issue #:* /bcgov/entity#4711

*Description of changes:*

* Added conversion ledger processor
* Added conversion ledger tests 
* Updated incorporation applications tests to test filings from Colin for LTDs, ULCs and CCCs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by argush3** [comment]
> SonarCloud Quality Gate failed.
> 
> [Bug](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=VULNERABILITY)
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=bcgov_lear&pullRequest=1159&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=bcgov_lear&pullRequest=1159&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=bcgov_lear&pullRequest=1159&resolved=false&types=SECURITY_HOTSPOT)
> [Code Smell](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=bcgov_lear&pullRequest=1159&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=bcgov_lear&pullRequest=1159) No Coverage information
> [](https://sonarcloud.io/component_measures?id=bcgov_lear&pullRequest=1159&metric=new_duplicated_lines_density&view=list) [35.7% Duplication](https://sonarcloud.io/component_measures?id=bcgov_lear&pullRequest=1159&metric=new_duplicated_lines_density&view=list)

The code duplication is because the conversion tests are essentially a copy of the incorporation application.

**Comment by thorwolpert** [comment]
If the get_corp and affiliation is to be re-used, it shouldn't be copy/pasted in without changes.
The affiliation uses a temp-reg, but that isn't created by the loader, so it wont work here.

**Comment by thorwolpert** [comment]
i've made a series of changes based on the conversion filings being a historical filing that is getting transferred over.
I'll update the tests in morning.

**Review by kialj876 — APPROVED** [review]
Nice work

**Comment by argush3** [comment]
Updates look good.

Thanks for stripping out the irrelevant logic and adding additional logic for processing of conversion filings.  🙏

**Comment by thorwolpert** [comment]
I think the specs were too lite, and always easier to fix than create.

**Pull request merged**
