### PR TITLE
DevOps - RC2

### PR DESCRIPTION
**Pull request by bsnopek-freshworks**
- Added NATS, entity-pay and entity-filer
- Corrected DB issues
- Updated several parameterization issues.

### CODE REVIEW

**Comment by WaldemarSchneider86** [comment]
Thor: "i've asked Roland to take over the reviews of this, so that it can be managed by the test/qa team."

**Comment by bsnopek-freshworks** [comment]
@rstens - Proper demo and integration is currently blocked due to cross-domain auth issues which are currently being resolved in entities-#2640 - With that one finished we should be able to do a full demo - expecting #2640 to be finished this sprint, and will reach out to you as soon as we're ready.

**Comment by rstens** [comment]
OK, great.

**Comment by katiemcgoff** [comment]
Closing - to be opened fresh when blockers cleared.

**Pull request closed without merging**
