### PR TITLE
14321 Allow filings for BC, CC, ULC

### PR DESCRIPTION
**Pull request by vysakh-menon-aot**
*Issue #:* /bcgov/entity#14321

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by vysakh-menon-aot** [comment]
lint failed due to flake8 issue

**Review by severinbeauvais — APPROVED** [review]
Looks fine to me.

I wonder if it would be good to sort all the keys you touched -- for easier human comparison?

Also, are we sure that these are the correct fee codes?

**Comment by severinbeauvais** [comment]
What's wrong with the failed checks above?

**Comment by argush3** [comment]
> What's wrong with the failed checks above?

Travis mentioned the linting issue in developer channel

**Comment by severinbeauvais** [comment]
> > What's wrong with the failed checks above?
> 
> Travis mentioned the linting issue in developer channel

OK, thanks. I see it now.

Should the imports be updated to pick up the fix or is this a CI thing?

**Comment by argush3** [comment]
It might be fixed now.  Seems like a new version was released over the weekend.

**Review by argush3 — APPROVED** [review]

**Review by lekshmimallika-aot — APPROVED** [review]

**Comment by severinbeauvais** [comment]
> It might be fixed now. Seems like a new version of flake8-isort was released over the weekend.

Yes! I restarted the failed checks and the linter issues are now gone. Nice.

**Pull request merged**
