### PR TITLE
Test PR - OAS CI workflow in api-spec-updates

### PR DESCRIPTION
**Pull request by eason-pan-bc**
*Issue #:* /bcgov/entity###

*Description of changes:*
Test PR - OAS CI workflow in api-spec-updates to see whether all checks work properly

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by chenhongjing** [comment]
No access permission to some file?

**Comment by AimeeGao** [comment]
> No access permission to some file?

We submitted a sample PR to see if the OAS CI workflow checks the linting, and did some tests.

**Comment by eason-pan-bc** [comment]
> No access permission to some file?

yeah, it looks like it might not have the necessary permissions to access the source repository (bcgov/bcregistry-sre)

**Comment by chenhongjing** [comment]
> > No access permission to some file?
> 
> yeah, it looks like it might not have the necessary permissions to access the source repository (bcgov/bcregistry-sre)

I mean, does the workflow require some write access after linting? Looks like there's no issue to copy `.spectral.yaml` from sre and then load files.
image

**Comment by eason-pan-bc** [comment]
> > > No access permission to some file?
> > 
> > 
> > yeah, it looks like it might not have the necessary permissions to access the source repository (bcgov/bcregistry-sre)
> 
> I mean, does the workflow require some write access after linting? Looks like there's no issue to copy `.spectral.yaml` from sre and then load files. image

Yeah, you are right, the linting works fine, and found some issues. Found the action file for spectral-action https://github.com/stoplightio/spectral-action/blob/master/action.yml
Based on it, it's less likely the error is due to the action trying to write results back to the repo. But not sure about the docker part. Gonna dig a bit more tomorrow

**Comment by eason-pan-bc** [comment]
will have a new test PR for updated ci workflow file

**Comment by chenhongjing** [comment]
New issue after you updated workflow file
image

**Pull request closed without merging**
