### PR TITLE
21124 Legal API - update allowable actions

### PR DESCRIPTION
**Pull request by AimeeGao**
*Issue #:* /bcgov/entity#21124

*Description of changes:*

- Update allowable actions to block following filings types if business is in dissolution. This [PR](https://github.com/bcgov/lear/pull/2481/files) is a good reference
  - Voluntary dissolution
  - Alteration
  - Amalgamation

-  Use new in_dissolution property in business model to help in determining if a business is in the process of being dissolved
-  Add/update unit tests as appropriate
-  Update [allowable actions spreadsheet](https://docs.google.com/spreadsheets/d/1sxsZ7vuODtD_ftjR27qLvgYErWDB-msvzGucjvBRQXQ/edit#gid=0) to include new rules

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by chenhongjing — APPROVED** [review]
LGTM 🐱  BTW, you don't have to copy all the things from description of ticket to PR's description of changes. Just briefly describe your code changes.

**Comment by AimeeGao** [comment]
> LGTM 🐱 BTW, you don't have to copy all the things from description of ticket to PR's description of changes. Just briefly describe your code changes.

Got it, thanks for the tip, I will keep it brief next time 😄

**Review by leodube-aot — APPROVED** [review]
LGTM!

**Review by argush3 — APPROVED** [review]

**Review by kzdev420 — APPROVED** [review]
LGTM

**Pull request merged**
