### PR TITLE
10161 conditional outputs

### PR DESCRIPTION
**Pull request by vysakh-menon-aot**
*Issue #:* /bcgov/entity#10161

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by lekshmimallika-aot — COMMENTED** [review]
Could you please update the tests as well?

**Comment by vysakh-menon-aot** [comment]
> Could you please update the tests as well?

Sure. I am waiting to get confirmation from @thorwolpert regarding this approach.

**Comment by lekshmimallika-aot** [comment]
> > Could you please update the tests as well?
> 
> Sure. I am waiting to get confirmation from @thorwolpert regarding this approach.

One of the questions I had was whether the filing metadata can be used for this? I know for business type alteration metadata gets populated correctly. If name change also does that may be we can use that?

**Review by thorwolpert — COMMENTED** [review]
The name change should be in the filing_meta, can we use that or update the meta for what is needed. the filing_json is an expensive call and the format is not guranteed.

**Review by thorwolpert — APPROVED** [review]

**Review by lekshmimallika-aot — APPROVED** [review]

**Pull request merged**
