### PR TITLE
18557 remove old fetch nr endpoint

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#18557

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
🎉

**Comment by argush3** [comment]
So we're sure that nothing uses this endpoint anymore?

**Comment by kzdev420** [comment]
> So we're sure that nothing uses this endpoint anymore?

We updated the Create, Edit, Filing-UI,

**Review by argush3 — APPROVED** [review]

**Comment by seeker25** [comment]
there's a spot in auth-web

image

**Comment by severinbeauvais** [comment]
> there's a spot in auth-web

Dang, good eye!

> Doesn't look used though

LOL, decoy pattern! Want to remove that some time?

**Comment by seeker25** [comment]
https://github.com/bcgov/sbc-auth/pull/2638

**Comment by severinbeauvais** [comment]
Argus, please merge this when you untangle yourself from the release branch stuff.

**Comment by seeker25** [comment]
@kzdev420 we still need this endpoint:

image

```
    @staticmethod
    def _get_nr_details(nr_number: str, token: str):
        """Return NR details by calling legal-api."""
        legal_api_url = current_app.config.get('LEGAL_API_URL') + current_app.config.get('LEGAL_API_VERSION_2')
        get_nr_url = f'{ legal_api_url }/nameRequests/{nr_number}'
        try:
            get_nr_response = RestService.get(get_nr_url, token=token, skip_404_logging=True)
        except (HTTPError, ServiceUnavailableException) as e:
            current_app.logger.info(e)
            raise BusinessException(Error.DATA_NOT_FOUND, None) from e
 
        return get_nr_response.json()
```

**Comment by seeker25** [comment]
https://github.com/bcgov/sbc-auth/pull/2639 <- WIP here

**Pull request merged**
