### PR TITLE
22949 update digital credentials to use new versioning

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#22949

*Description of changes:*

- Replaced the code to initialize and use the new db versioning
- Updated configuration to support feature flags
- Added flags.json file
- Updated requirements.txt with necessary dependencies
- Switch the versioning Proxy

Unit Test
**1. Flag is ON:**

**- Proxy Check**
Screenshot 2024-12-09 at 9 38 56 AM

**- Unit Test**
Screenshot 2024-12-09 at 9 09 21 AM

**2. Flag is OFF:**

**- Proxy Check**
Screenshot 2024-12-09 at 9 09 54 AM

**- Unit Test**
Screenshot 2024-12-09 at 9 10 29 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by kzdev420** [comment]
> The first screenshot (Flag is ON - Proxy Check) looks like running involuntary-dissolution. Can you provide a screenshot showing using Proxy when FF is ON and running digital credential queue service?

Sorry, I just updated the screenshot

**Review by eason-pan-bc — CHANGES_REQUESTED** [review]
There are uses of `versioning_manager` in its unit tests. Please make sure you have switched to use the new db-versioning
**For example:** 
- https://github.com/bcgov/lear/blob/feature-db-versioning/queue_services/entity-digital-credentials/tests/unit/__init__.py#L17C33-L17C51
- https://github.com/bcgov/lear/blob/feature-db-versioning/queue_services/entity-digital-credentials/tests/unit/__init__.py#L39

Check if there are other places and other things need to be updated

**Review by eason-pan-bc — COMMENTED** [review]
There are also some linting issues, please fix them

**Review by AimeeGao — APPROVED** [review]
LGTM👍

**Review by eason-pan-bc — APPROVED** [review]

**Pull request merged**
