### PR TITLE
18720 remove colin api auth on/off FF

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#17820

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by argush3** [comment]
I think we can remove the `disable-colin-api-auth` property from flags.json

https://github.com/bcgov/lear/blob/ac90e01380c939adc09b00029f50403485074761/colin-api/flags.json#L3

**Comment by argush3** [comment]
please remove `conditional_auth` decorator altogether

https://github.com/bcgov/lear/blob/ac90e01380c939adc09b00029f50403485074761/colin-api/src/colin_api/utils/util.py#L38-L60

**Comment by argush3** [comment]
we can remove [test_util_conditional_auth.py](https://github.com/bcgov/lear/blob/ac90e01380c939adc09b00029f50403485074761/colin-api/tests/unit/utils/test_util_conditional_auth.py)

**Comment by argush3** [comment]
import statements for every resource file that used conditional_auth decorator can be deleted.

**Comment by kzdev420** [comment]
Hi all

https://github.com/bcgov/lear/blob/757a8f7bd2532b188ed3320e72f6b0c7f0203bd7/colin-api/requirements/dev.txt#L22

To fix the current lint issue, this line should be updated like this.
`pylint`. remove this `<=2.3.1`
Then it will install the `pylint-3.0.2-py3-none-any.whl`

I checked it gets rid of `AttributeError: module 'astroid' has no attribute 'TryExcept'`. but there are some new lint-errors that should be fixed.

**Comment by argush3** [comment]
@kzdev420 please update dev.txt as you had mentioned above and let's see what new linting errors you get.  

For colin-api, we typically don't spend that much effort in fixing linting errors as we colin-api will be going away.

**Review by argush3 — APPROVED** [review]

**Pull request merged**
