### PR TITLE
13058 COLIN API failure - Front and Backend Change validation of the first name field in Coop IA UI and/or Corp Party table

### PR DESCRIPTION
**Pull request by lewischenstudio**
*Issue #:* [/bcgov/entity#13058](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13058)

*Description of changes:*
- added unit test for schema change: [first_name and middle_name](https://github.com/bcgov/business-schemas/pull/101/files)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by vysakh-menon-aot** [comment]
Update schema version here
https://github.com/bcgov/lear/blob/main/legal-api/requirements/bcregistry-libraries.txt#L1
https://github.com/bcgov/lear/blob/main/legal-api/requirements.txt#L61

**Comment by lewischenstudio** [comment]
> Update schema version here https://github.com/bcgov/lear/blob/main/legal-api/requirements/bcregistry-libraries.txt#L1 https://github.com/bcgov/lear/blob/main/legal-api/requirements.txt#L61

I updated the schema version from 2.15.27 to 2.15.29, which I got from [here](https://github.com/bcgov/business-schemas/blob/395e2c90b28051ce14758f0fd06ef593baa9dbf3/src/registry_schemas/version.py#L25). Is this the correct version to use?

**Comment by vysakh-menon-aot** [comment]
> > Update schema version here https://github.com/bcgov/lear/blob/main/legal-api/requirements/bcregistry-libraries.txt#L1 https://github.com/bcgov/lear/blob/main/legal-api/requirements.txt#L61
> 
> I updated the schema version from 2.15.27 to 2.15.29, which I got from [here](https://github.com/bcgov/business-schemas/blob/395e2c90b28051ce14758f0fd06ef593baa9dbf3/src/registry_schemas/version.py#L25). Is this the correct version to use?

Yes 👍

**Comment by lewischenstudio** [comment]
> > > Update schema version here https://github.com/bcgov/lear/blob/main/legal-api/requirements/bcregistry-libraries.txt#L1 https://github.com/bcgov/lear/blob/main/legal-api/requirements.txt#L61
> > 
> > 
> > I updated the schema version from 2.15.27 to 2.15.29, which I got from [here](https://github.com/bcgov/business-schemas/blob/395e2c90b28051ce14758f0fd06ef593baa9dbf3/src/registry_schemas/version.py#L25). Is this the correct version to use?
> 
> Yes 👍

Nice. Thanks 🙏

**Review by vysakh-menon-aot — APPROVED** [review]

**Pull request merged**
