### PR TITLE
22499 Configurations - Alembic script to add furnishings SFTP configurations

### PR DESCRIPTION
**Pull request by leodube-aot**
*Issue #:* /bcgov/entity#22499

*Description of changes:*
- Created alembic script to add furnishings SFTP configurations (to address [Argus' comment](https://app.zenhub.com/workspaces/entities---david-65af11a89e89f5043c2911f6/issues/gh/bcgov/entity/22498) in the SFTP spike ticket)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by chenhongjing** [comment]
The other [PR](#2964) looks good, but I'm still thinking about this one... 💭 

Although as Argus mentioned, we need to turn SFTP on and off, flag values in db are more easily changed by accident, as many people have access. Servers of BCLaws and BCMail+ are primitive. I'm worried about what will happen if we transfer unnecessary files to them. 

What do you think of it? What about just skipping the SFTP process if there's no value set in `.env`?

**Comment by leodube-aot** [comment]
> What do you think of it? What about just skipping the SFTP process if there's no value set in `.env`?

That's a good point. I'm okay with just skipping the SFTP process if there is no `.env` connection values set. @argush3 what are your thoughts on doing this vs. having db config values?

**Comment by argush3** [comment]
> > What do you think of it? What about just skipping the SFTP process if there's no value set in `.env`?
> 
> That's a good point. I'm okay with just skipping the SFTP process if there is no `.env` connection values set. @argush3 what are your thoughts on doing this vs. having db config values?

After thinking and talking with Hongjing about this a bit, I think we can use 2 feature flags
* `disable-dissolution-sftp-bcmail`
* `disable-dissolution-sftp-bclaws` feature flags.  

Hongjing has created the two flags in LD already.

The flags will be turned on in dev/test/prod for now to disable SFTP.   When we go live, we can turn off the 2 flags for prod so SFTP works.

As for dev & test, assuming things are configured correctly in 1pass config for the SFTP staging servers for BCLaws & BCMail+, we can toggle on the corresponding flag when we need to test SFTP functionality.

**Comment by leodube-aot** [comment]
Closing this PR, and will update the other PR to handle the feature flags

**Pull request closed without merging**
