### PR TITLE
23222 comment out 1pass update section by 20241001 all BE

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#23222

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by chenhongjing** [comment]
@vysakh-menon-aot some questions to confirm something. I remember that we don't use `entity-pay` and but are using `business-pay` now. Is it correct? And should `business-pay` be manually deployed? Or do we had better not touch it for now?

**Comment by vysakh-menon-aot** [comment]
> @vysakh-menon-aot some questions to confirm something. I remember that we don't use `entity-pay` and but are using `business-pay` now. Is it correct? And should `business-pay` be manually deployed? Or do we had better not touch it for now?

Right entity-pay is deprecated. Yes business-pay has to be manually deployed.

**Comment by vysakh-menon-aot** [comment]
> Hi @chenhongjing @vysakh-menon-aot
> 
> Reverted the changes for the business-pay and entity-pay

You need to update business-pay

**Comment by chenhongjing** [comment]
You don't need to comment out 1password sections for `data-reset-tool`, `data-tool`, `filings-notebook-report`, `sftp-gazette`, `sftp-icbc-report`, `sftp-nuans-report`, `entity-pay`, so just revert this change. And we should keep the updates for `business-pay`. But you have to deploy it manually.

See Vysakh's comments.

**Comment by kzdev420** [comment]
> sftp

Reverted these BE components

**Review by chenhongjing — APPROVED** [review]

**Review by eason-pan-bc — APPROVED** [review]
Based on the conversations, looks good

**Review by JazzarKarim — APPROVED** [review]
LGTM

**Pull request merged**
