### PR TITLE
18240 - Fixed Expiring Soon Emails

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:* /bcgov/entity#18240

*Description of changes:*
- Moving the Names team commit to the release branch that Sev created

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Comment by JazzarKarim** [comment]
Sev, don't worry about the lint issues. I discovered them in my emailer PR and fixed them there: https://github.com/bcgov/lear/pull/2327

They carried over from previous PRs. I'm assuming names team work.

**Comment by severinbeauvais** [comment]
@argush3 This is the same as https://github.com/bcgov/lear/pull/2324 but against the release branch, so that it can be pushed to Dev and then Test asap. Riyaz is OK with it.

(Names team committed this after our release cutoff, but they need it in Prod before Tuesday.)

**Comment by severinbeauvais** [comment]
@argush3 Karim says the lint issues are pre-existing but he will fix them in https://github.com/bcgov/lear/pull/2327.

**Review by severinbeauvais — APPROVED** [review]
Looks the same as the original PR.

**Pull request merged**
