### PR TITLE
14284 Restrict ULC/CCC to custom Incorporation Agreement only

### PR DESCRIPTION
**Pull request by ChrisGabel23**
*Issue #:* /bcgov/entity#14284 

*Description of changes:*
- added validation for ULC/CCC to only allow for custom Incorporation Agreements

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

### CODE REVIEW

**Review by vysakh-menon-aot — APPROVED** [review]

**Review by thorwolpert — APPROVED** [review]
looks covered to me.
we don't lint the test files, but should try and keep them close, so a small thing is the file must end in an empty line.

**Review by argush3 — APPROVED** [review]

**Comment by ChrisGabel23** [comment]
> looks covered to me. we don't lint the test files, but should try and keep them close, so a small thing is the file must end in an empty line.

Both of my local files ended with an empty line. Is there something I need to do to ensure the repo sees this? Do I need to add a space on that line?

**Comment by ChrisGabel23** [comment]
Are there any concerns that I'm adding a Critical level code smell? It's one of those "code complexity" ones and I'm not sure how to reduce the complexity.

**Comment by ChrisGabel23** [comment]
> Are there any concerns that I'm adding a Critical level code smell? It's one of those "code complexity" ones and I'm not sure how to reduce the complexity.

As discussed at the stand-up, this is okay to merge as is.

**Pull request merged**
